# Data for docs/v2/execution-order.md, rendered by gen_execution_order.py.
# One primary workstream ("club") per sprint; `also` lists sprints that share a club's work.

FAMILIES = [
    # id, name, when
    ("found", "Foundations", "Sep 25 – Oct 30"),
    ("engine", "Learning engine", "late Oct – Nov"),
    ("judgefam", "Judge", "Oct – Dec"),
    ("aifam", "Platform AI", "Oct spike · Dec build"),
    ("gatefam", "Learner gate & GA", "Nov – Jan"),
    ("ivfam", "Interviewer (v2.1)", "Q1 2027"),
    ("cross", "Cross-cutting", "all along"),
    ("laterfam", "Later", "H2 2027 · v2.2"),
]

# club id, family, emoji, name, what the club brings (one line), also-shared sprints
CLUBS = [
    ("guard",  "found",   "🛡️", "Cluster guardrails & fences",
     "Data-loss guards, chart knobs, NetworkPolicy fences, consoles off xLearn's origin, limit hygiene", []),
    ("nats",   "found",   "📨", "NATS auth & event plumbing",
     "Per-service nkeys + ACLs, dead letters, identity on NATS — precondition for erase and the judge", ["mi-11"]),
    ("spine",  "found",   "🧭", "Curriculum spine (multi-course)",
     "Course manifest, frozen item schema, path_slug everywhere, course routing — no behaviour change", ["p-02"]),
    ("sec",    "found",   "🔐", "Security floor",
     "Roles in the DB, admin CLI, revocable sessions, typed limits, withhold(), safe Markdown", []),
    ("coach",  "found",   "💬", "Coach v2",
     "Per-feature keys, provider hygiene, assist capture, BYO caps", []),
    ("touch",  "engine",  "🔁", "Touch engine & projections",
     "Revision touches become real timed attempts, projections v2, the D2 ladder rule, Today in minutes", []),
    ("public", "engine",  "🌐", "Public profile v2",
     "public-read authority, visibility toggles, count-only mocks, judge-checked %", ["m1-05", "m3-10"]),
    ("packs",  "judgefam", "📦", "Eval packs & authoring tooling",
     "Private eval-pack repo, packlint + pre-push fingerprint hook, the pack pipeline", []),
    ("runner", "judgefam", "🧪", "Sandbox & runner",
     "Spike-proven jail, host sandbox block, Go/C++/Python runner, runner-v1.0.0 dark on prod", ["p-01"]),
    ("judge",  "judgefam", "⚖️", "Judge service",
     "The 8th service: queue, graders, admission, learner API; practice/review/assessment consume its evidence", ["l-01"]),
    ("judgeui","judgefam", "🖥️", "Judge UI",
     "Workspace-Code ★, results dock, Problems/Arena, degradation badges — judge on for the owner", []),
    ("pilot",  "judgefam", "🧵", "Pilot course: go-concurrency",
     "go-race profile, the 2nd course as manifest + content, quiz + race verdict", []),
    ("ai",     "aifam",   "✨", "Platform AI",
     "WIF credential, shared LLM layer, Scorer + ledger, analyzer, provisional grades, consents", []),
    ("gate",   "gatefam", "🚪", "Learner gate (built now, opened in v3)",
     "Erase end to end, invite-only admission, acceptance step + notice, production rehearsal", ["m3-05", "mi-04"]),
    ("ga",     "gatefam", "🏁", "v2.0 GA",
     "The owner-facing default flip: judge + platform AI on, pilot active → v2.0.0", []),
    ("ivtext", "ivfam",   "🎙️", "Interviewer: text (M6a)",
     "Interview core with failsafes, text brain, one honest mock score, coding rounds, UI", []),
    ("ivvoice","ivfam",   "🔊", "Interviewer: voice (M6b)",
     "Voice shell with no media on the node, robustness + cost cap, voice UI → v2.1.0", []),
    ("design", "cross",   "🎨", "Design boards",
     "Agent-drafted artboards, one milestone ahead; the merge is the freeze (D40)", []),
    ("later",  "laterfam","⏭️", "Later",
     "DSA evaluator-only (M5) once every item is packed; v2.2 interviewer extras", []),
]

WAVES = [
    ("W1",  "Week 1", "Sep 25 – Oct 2"),
    ("W2",  "Week 2", "Oct 5 – 9"),
    ("W3",  "Week 3 · spike week", "Oct 12 – 16"),
    ("W4",  "Week 4", "Oct 17 – 23"),
    ("W5",  "Late Oct · host window Sat Oct 24", "Oct 24 – Nov 1"),
    ("W6",  "Early Nov", "Nov 2 – 8"),
    ("W7",  "Mid Nov", "Nov 9 – 20"),
    ("W8",  "Late Nov", "Nov 21 – 30"),
    ("W9",  "December", "Dec 1 – 23"),
    ("W10", "GA", "late Dec – Jan"),
    ("W11", "v2.1", "Q1 2027"),
    ("W12", "Later", "H2 2027 · v2.2"),
]

# order, id, club, wave, brings, cuts (tag it cuts or ""), lane
SPRINTS = [
    (1,  "mi-01",    "guard",  "W1", "Data-loss guards on DB + NATS, chart 0.3.0 knobs (no pod rolls)", "", "infra"),
    (2,  "ds-m1-01", "design", "W1", "Boards AB01–AB03: coach states, course nav, revision v2", "", "design"),
    (3,  "mi-02",    "guard",  "W1", "host-verify --cluster: on-demand cluster checks (the only ops tool)", "", "infra"),
    (4,  "m1-01",    "spine",  "W1", "Prod-parity compose, course manifest + golden, frozen item schema", "", "product"),
    (5,  "mi-07",    "packs",  "W1", "Private eval-pack repo, machine user, GHCR, pull secret", "", "infra"),
    (6,  "ds-m2-01", "design", "W1", "Boards AB04★ Touch, AB05 catalog/agenda, AB06 profile, AB22", "", "design"),
    (7,  "ds-l-01",  "design", "W1", "Boards AB19★ invite acceptance, AB20 notice, AB21 erase", "", "design"),
    (8,  "m1-09",    "spine",  "W2", "Curriculum converter, loader + guards, expand migration, content CI", "", "product"),
    (9,  "m3-01",    "packs",  "W2", "Authoring tooling: packlint, contract_hash, pre-push fingerprint hook", "", "content"),
    (10, "mi-05",    "nats",   "W2", "N0 (dark): NATS topology, dead letters, identity on NATS", "", "product"),
    (11, "m1-02",    "spine",  "W2", "path_slug everywhere + v2 envelope consumers", "v1.6.0", "product"),
    (12, "mi-14",    "runner", "W2", "Empty default-deny xlearn-runner namespace + admission policy", "", "infra"),
    (13, "mi-03",    "guard",  "W2", "NetworkPolicy fences: databases, messaging, xlearn ingress", "", "infra"),
    (14, "m3-02",    "packs",  "W2", "Eval-pack pipeline: validation gates, data image, fixture pack", "", "content"),
    (15, "mi-04",    "guard",  "W2", "Admin consoles move to ops.sujaykumar.dev", "", "infra"),
    (16, "spk-01",   "runner", "W3", "Spike: sandbox mechanism P0–P2 (throwaway)", "", "spike"),
    (17, "spk-02",   "runner", "W3", "Spike: amd64 replay + eval-pack image volume (throwaway)", "", "spike"),
    (18, "spk-03",   "ai",     "W3", "Spike: WIF credential for platform AI (throwaway)", "", "spike"),
    (19, "mi-06",    "nats",   "W3", "NATS auth live: nkey users + ACLs, legacy closed (N1–N3)", "", "infra"),
    (20, "m1-03",    "spine",  "W3", "Course resolution end to end; DSA stays pixel-identical", "", "product"),
    (21, "m1-04",    "sec",    "W3", "Roles in DB, revocable sessions, admin CLI, CSP, DEV_AUTH guard", "", "product"),
    (22, "m1-10",    "coach",  "W3", "Coach keys: per-feature defaults, catalog, AEAD keyring, typed errors", "", "product"),
    (23, "m1-05",    "sec",    "W3", "Typed 429/413 limits + public-profile floor (count-only mocks)", "", "product"),
    (24, "m1-06",    "sec",    "W3", "withhold() on every route, safe Markdown, revision v2", "", "product"),
    (25, "mi-08",    "guard",  "W4", "Limit hygiene (≈ −3 GiB), PSA labels, SA tokens off", "", "infra"),
    (26, "mi-09",    "runner", "W4", "Host-window prep: sandbox host block, kubelet reservation (Sat Oct 24)", "", "infra"),
    (27, "m1-07",    "coach",  "W4", "Coach assist capture, mode gate, BYO caps", "v1.7.0", "product"),
    (28, "ds-m3-01", "design", "W4", "Boards AB07★ workspace, AB08 results dock, AB11 badges", "", "design"),
    (29, "m1-08",    "spine",  "W5", "M1 contract: drop the v1 columns (snapshot first)", "v1.8.0", "product"),
    (30, "m3-03",    "runner", "W5", "Runner core: supervisor, jail, per-case cgroups, job API", "", "product"),
    (31, "m3-04",    "runner", "W5", "Runner profiles Go/C++/Python + harness codecs", "", "product"),
    (32, "m3-15",    "runner", "W5", "Reproducible runner image + acceptance suite", "runner-v1.0.0", "product"),
    (33, "m2-01",    "touch",  "W5", "Touches become real attempts + review consumer", "", "product"),
    (34, "m2-02",    "touch",  "W5", "M2 consumers + projections v2 (producers idle)", "v1.9.0", "product"),
    (35, "ds-m3-02", "design", "W5", "Boards AB09 Problems, AB10 Arena, AB12 progress deltas", "", "design"),
    (36, "m2-03",    "public", "W5", "public-read, /public/stats, visibility toggles, profile v2", "", "product"),
    (37, "m2-04",    "touch",  "W5", "Touch UI ★ + cross-course Today/agenda in minutes", "", "product"),
    (38, "m2-05",    "touch",  "W6", "Producers on, backfill, replay, D2 ladder rule", "v1.10.0", "product"),
    (39, "l-01",     "gate",   "W6", "Erase consumers in every service", "v1.11.0", "product"),
    (40, "l-02",     "gate",   "W6", "Erase producer + DELETE /api/me (testers only)", "v1.12.0", "product"),
    (41, "mi-10",    "runner", "W6", "runner-v1.0.0 dark on production + acceptance suite", "", "infra"),
    (42, "m3-05",    "judge",  "W6", "judge service: skeleton, schema, pack loader, erase consumer", "", "product"),
    (43, "m3-06",    "judge",  "W6", "judge core: queue, runner lane, graders, contexts", "", "product"),
    (44, "m3-14",    "judge",  "W7", "judge admission control, learner API, drafts, arena history", "", "product"),
    (45, "ds-p-01",  "design", "W7", "Boards AB14 quiz, AB15 race view; AB02/AB05 full fidelity", "", "design"),
    (46, "m3-07",    "judge",  "W7", "judge on prod (dark): evalpack v1.0.0, ACL, HelmRelease", "v1.13.0", "product"),
    (47, "l-03",     "gate",   "W7", "Invite admission backend (inert while signup is closed)", "", "product"),
    (48, "m3-08",    "judge",  "W7", "practice consumes judge evidence; the 45:00 method", "", "product"),
    (49, "m3-09",    "judge",  "W7", "Gateway judge BFF, DTO deny-list, typed limits", "", "product"),
    (50, "m3-10",    "judge",  "W7", "review + assessment on judge signals (pre-fill, judge-checked %)", "", "product"),
    (51, "ds-m4-01", "design", "W7", "Boards AB16★ AI suggestion/dispute, AB17, AB18", "", "design"),
    (52, "mi-11",    "guard",  "W7", "Track B finish: egress, PG connection limits, Renovate, N4", "", "infra"),
    (53, "m3-11",    "judgeui","W8", "Workspace-Code UI ★ + lazy CodeMirror", "", "product"),
    (54, "m3-12",    "judgeui","W8", "Results dock, Problems, Arena, degradation badges", "", "product"),
    (55, "m3-13",    "judgeui","W8", "Progress deltas + M3 exit tests; judge on for the owner", "v1.14.0", "product"),
    (56, "mi-12",    "ai",     "W9", "M4 gates: judge 443 egress, LLM secret, provider runbook", "", "infra"),
    (57, "p-01",     "pilot",  "W9", "go-race runner profile", "runner-v1.1.0", "product"),
    (58, "p-02",     "pilot",  "W9", "go-concurrency course as manifest (preview) + multi-course nav", "", "product"),
    (59, "p-03",     "pilot",  "W9", "Quiz + race verdict UI", "v1.15.0", "product"),
    (60, "m4-01",    "ai",     "W9", "Shared LLM layer + WIF auth + retention policy", "", "product"),
    (61, "m4-02",    "ai",     "W9", "judge AI engine: Scorer, ledger, llm lane, caps", "", "product"),
    (62, "m4-03",    "ai",     "W9", "Analyzer on concluded attempts + acceptance-set harness", "", "product"),
    (63, "m4-04",    "ai",     "W9", "Provisional grades, dispute, re-grade, honor claims", "", "product"),
    (64, "m4-05",    "ai",     "W9", "AI allowance + consents", "", "product"),
    (65, "m4-06",    "ai",     "W9", "AI UI ★: suggestion/dispute, pointer notes, allowance", "", "product"),
    (66, "m4-07",    "ai",     "W9", "Canary + caps sizing; platform AI on for the owner", "v1.16.0", "product"),
    (67, "l-05",     "gate",   "W9", "Invite front door: acceptance step ★, privacy notice, AI consents", "", "product"),
    (68, "l-04",     "gate",   "W9", "Web erase for non-owners + invite rehearsal on prod", "v1.17.0", "product"),
    (69, "ga-01",    "ga",     "W10", "GA PR: .release-line = 2, default flips, rc rehearsal", "", "product"),
    (70, "ga-02",    "ga",     "W10", "Widen ranges, snapshot, tag, verify", "v2.0.0", "product"),
    (71, "spk-04",   "ivtext", "W11", "Spike S6: voice-shell bake-off (owner present)", "", "spike"),
    (72, "ds-m6a-01","design", "W11", "Accept ADR-0032 + boards AB13, AB24, AB25", "", "design"),
    (73, "ds-m6a-02","design", "W11", "Boards AB26 grace/pause, AB27 debrief, AB28 a11y", "", "design"),
    (74, "m6a-01",   "ivtext", "W11", "Interview core: state machine, failsafes, caps", "", "product"),
    (75, "m6a-02",   "ivtext", "W11", "Text brain on the learner's key + replay tests", "", "product"),
    (76, "m6a-03",   "ivtext", "W11", "Mock scoring: proposal → accept → ScoreMock once", "", "product"),
    (77, "m6a-04",   "ivtext", "W11", "Coding rounds via judge mock + editor interview mode", "", "product"),
    (78, "m6a-05",   "ivtext", "W11", "Interviewer UI part 1: setup, consent, text HUD", "", "product"),
    (79, "m6a-06",   "ivtext", "W11", "Interviewer UI part 2 + M6a exit (dark)", "v2.0.x", "product"),
    (80, "ds-m6b-01","design", "W11", "Boards AB29 voice pre-flight, AB30★ voice HUD", "", "design"),
    (81, "mi-13",    "ivvoice","W11", "Voice platform gates: Permissions-Policy, SDP route, egress", "v2.0.x", "infra"),
    (82, "m6b-01",   "ivvoice","W11", "Voice shell + SDP broker + sideband (no media on the node)", "", "product"),
    (83, "m6b-02",   "ivvoice","W11", "Voice robustness: lease, drain, cost cap, push-to-talk", "", "product"),
    (84, "m6b-03",   "ivvoice","W11", "Voice UI + browser/EU gates (dark)", "v2.0.x", "product"),
    (85, "m6b-04",   "ivvoice","W11", "Fake-media e2e + interviewer flip", "v2.1.0", "product"),
    (86, "m5-01",    "later",  "W12", "DSA evaluator-only flip (once every item is packed)", "≥ v2.2.0", "product"),
    (87, "m6c-01",   "later",  "W12", "v2.2 outline: show-your-work photo, read-aloud, local download", "", "outline"),
    (88, "m6c-02",   "later",  "W12", "v2.2 outline: fairness check → AI voice Communication", "", "outline"),
    (89, "m6c-03",   "later",  "W12", "v2.2 outline: Safari, voice-lite, canvas board (SD course)", "", "outline"),
]

# Tag train: tag → (sprint that cuts it, what it carries)
TAGS = [
    ("v1.6.0",        "m1-02", "M1a expand: spine part 1–2, N0 dark, authoring tooling"),
    ("v1.7.0",        "m1-07", "M1b: course resolution, security floor, coach v2"),
    ("v1.8.0",        "m1-08", "M1c contract (snapshot first)"),
    ("runner-v1.0.0", "m3-15", "Runner: core + Go/C++/Python profiles"),
    ("v1.9.0",        "m2-02", "M2 consumers + projections v2"),
    ("v1.10.0",       "m2-05", "M2 producers on, public-read, Touch UI, D2"),
    ("v1.11.0",       "l-01",  "Erase consumers"),
    ("v1.12.0",       "l-02",  "Erase producer (snapshot first)"),
    ("v1.13.0",       "m3-07", "judge dark + evalpack v1.0.0"),
    ("v1.14.0",       "m3-13", "judge Run/Submit + UI; judge on for the owner"),
    ("runner-v1.1.0", "p-01",  "go-race profile"),
    ("v1.15.0",       "p-03",  "Pilot course (preview)"),
    ("v1.16.0",       "m4-07", "Platform AI on for the owner"),
    ("v1.17.0",       "l-04",  "Invite front door + web erase (rehearsed)"),
    ("v2.0.0",        "ga-02", "GA: owner-facing default flip"),
    ("v2.0.x",        "m6a-06 · mi-13 · m6b-03", "Interviewer patches, dark"),
    ("v2.1.0",        "m6b-04", "Interviewer GA"),
]

# Design board → UI sprints that consume it
DESIGN_FEEDS = {  # from build-plan.md "Artboard register" (Consumed by), grouped by drafting sprint
    "ds-m1-01": ["m1-03", "m1-06", "m1-10", "m1-07"],
    "ds-m2-01": ["m2-01", "m2-03", "m2-04"],
    "ds-l-01":  ["l-02", "l-05"],
    "ds-m3-01": ["m3-11", "m3-12", "m5-01"],
    "ds-m3-02": ["m3-12", "m3-13"],
    "ds-p-01":  ["p-02", "p-03"],
    "ds-m4-01": ["m4-06"],
    "ds-m6a-01": ["m6a-05"],
    "ds-m6a-02": ["m6a-06"],
    "ds-m6b-01": ["m6b-03"],
}

# Workstream-level dependencies for the big-picture map (from → to, label)
CLUB_EDGES = [
    ("guard", "runner", "fences"),
    ("guard", "gate", "consoles off-origin"),
    ("nats", "gate", "erase needs N3"),
    ("nats", "judge", "judge ACL"),
    ("spine", "touch", ""),
    ("spine", "packs", "schema freeze"),
    ("sec", "gate", "roles + CLI"),
    ("coach", "ivtext", "keys"),
    ("touch", "judge", ""),
    ("packs", "judge", "pack image"),
    ("runner", "judge", "runner lane"),
    ("judge", "judgeui", ""),
    ("judge", "public", "judge-checked %"),
    ("judgeui", "pilot", ""),
    ("judge", "ai", ""),
    ("pilot", "ga", ""),
    ("ai", "ga", ""),
    ("gate", "ga", ""),
    ("ga", "ivtext", ""),
    ("ivtext", "ivvoice", ""),
    ("ga", "later", ""),
]

# Calendar events (owner) for the timeline
EVENTS = [
    ("H0 reboot", "2026-09-25"),
    ("Spike week", "2026-10-12", "2026-10-16"),
    ("Host window", "2026-10-24"),
]
