package packspec

import (
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path"
	"path/filepath"
	"sort"
	"strings"
)

// The builder (t1 §3.3): build/ is the image root plus its generated Dockerfile.
//
//	build/manifest.json
//	build/courses/<slug>/items/<id>/cases.jsonl.zst
//	build/courses/<slug>/items/<id>/{keys,anchors,exemplars}/**     (only where present)
//	build/Dockerfile                                                (not in the image)
//
// Only review-stamped items are built (the stamp gate): an unstamped item stays out of the
// pack, so judge grades it as self until its tests are stamped. Nothing else of the source
// — generators, validators, invalid inputs, submissions, edge.jsonl, pack.json, tests.lock,
// timing.json, drafts — ever reaches build/ (the listing test checks the image too).

// DockerfileName is the generated Dockerfile's name in the build directory.
const DockerfileName = "Dockerfile"

// ImageSource is the image's org.opencontainers.image.source label.
const ImageSource = "https://github.com/sujaykumarsuman/xlearn-evalpack"

// BuiltItem is one item to build: its materialized cases and the public grader kinds.
type BuiltItem struct {
	Materialized *Materialized
	GraderKinds  []string
}

// BuildOptions are the build's identity.
type BuildOptions struct {
	Out              string
	Version          string
	ValidatedAgainst string
	// Dockerfile writes build/Dockerfile (off for the compose fixture pack, which is mounted
	// as a directory).
	Dockerfile bool
}

// Build writes the built pack. Out must not exist or be empty.
func Build(items []BuiltItem, opt BuildOptions) (*Manifest, error) {
	if !semverRe.MatchString(opt.Version) {
		return nil, fmt.Errorf("--version %q is not MAJOR.MINOR.PATCH", opt.Version)
	}
	if !shaRe.MatchString(opt.ValidatedAgainst) {
		return nil, fmt.Errorf("--validated-against %q is not a 40-hex commit sha", opt.ValidatedAgainst)
	}
	if ents, err := os.ReadDir(opt.Out); err == nil && len(ents) > 0 {
		return nil, fmt.Errorf("--out %s is not empty", opt.Out)
	} else if err != nil && !errors.Is(err, os.ErrNotExist) {
		return nil, err
	}
	m := &Manifest{FormatMajor: FormatMajor, Version: opt.Version, ValidatedAgainst: opt.ValidatedAgainst, Items: map[string]ManifestItem{}}
	courses := map[string]bool{}
	for _, bi := range items {
		mat := bi.Materialized
		src := mat.Src
		if !src.Pack.Stamped() {
			return nil, fmt.Errorf("%s: not review-stamped (only stamped items are built)", src.Key())
		}
		base := path.Join("courses", src.Course, "items", src.ID)
		files := map[string]string{}
		cases, err := EncodeCases(mat.Cases)
		if err != nil {
			return nil, err
		}
		if err := writeFile(opt.Out, path.Join(base, CasesFile), cases); err != nil {
			return nil, err
		}
		files[path.Join(base, CasesFile)] = FileHash(cases)
		for _, dir := range builtDirs {
			root := filepath.Join(src.Dir, dir)
			err := filepath.WalkDir(root, func(p string, d fs.DirEntry, err error) error {
				if errors.Is(err, fs.ErrNotExist) && p == root {
					return fs.SkipDir
				}
				if err != nil {
					return err
				}
				if strings.HasPrefix(d.Name(), ".") {
					return fmt.Errorf("%s: dotfiles are not allowed in a pack", p)
				}
				if d.IsDir() {
					return nil
				}
				if !d.Type().IsRegular() {
					return fmt.Errorf("%s: only regular files ship", p)
				}
				rel, _ := filepath.Rel(src.Dir, p)
				rel = filepath.ToSlash(rel)
				b, err := os.ReadFile(p)
				if err != nil {
					return err
				}
				if err := writeFile(opt.Out, path.Join(base, rel), b); err != nil {
					return err
				}
				files[path.Join(base, rel)] = FileHash(b)
				return nil
			})
			if err != nil {
				return nil, err
			}
		}
		kinds := append([]string{}, bi.GraderKinds...)
		sort.Strings(kinds)
		acc := append([]string{}, src.Pack.AcceptsContractHashes...)
		m.Items[src.ID] = ManifestItem{ItemHash: ItemHash(files), AcceptsContractHashes: acc, GraderKinds: kinds, Files: files}
		courses[src.Course] = true
	}
	mb, err := m.Encode()
	if err != nil {
		return nil, err
	}
	if err := writeFile(opt.Out, ManifestFile, mb); err != nil {
		return nil, err
	}
	if opt.Dockerfile {
		if err := writeFile(opt.Out, DockerfileName, Dockerfile(sortedKeys(courses))); err != nil {
			return nil, err
		}
	}
	return m, nil
}

// Dockerfile is the generated image recipe: FROM scratch, one COPY (one layer) per course
// in sorted order, then the manifest.
func Dockerfile(courses []string) []byte {
	var b strings.Builder
	b.WriteString("# Generated by packlint build (xlearn internal/packspec). Do not edit.\n")
	b.WriteString("FROM scratch\n")
	b.WriteString("LABEL org.opencontainers.image.source=" + ImageSource + "\n")
	sort.Strings(courses)
	for _, c := range courses {
		fmt.Fprintf(&b, "COPY courses/%s/ /courses/%s/\n", c, c)
	}
	b.WriteString("COPY manifest.json /manifest.json\n")
	return []byte(b.String())
}

func writeFile(root, rel string, b []byte) error {
	p := filepath.Join(root, filepath.FromSlash(rel))
	if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
		return err
	}
	return os.WriteFile(p, b, 0o644)
}
